### ISSUE TITLE
Align media image to left

### ISSUE THREAD

**Issue by AaronLayton** [PolymerLabs/paper-card#5]
Add the ability to align the media image to the left (or right) and the header to the right as per below

![2015-02-12_21h02_06](https://cloud.githubusercontent.com/assets/694964/6176918/691e328a-b2fa-11e4-86f7-b846cdc71397.png)

**Comment by addyosmani** [comment]
We've since migrated this element to https://github.com/PolymerElements/paper-card. Could you refile this issue there if it's still valid?
