### ISSUE TITLE
Automatic card color

### ISSUE THREAD

**Issue by AaronLayton** [PolymerLabs/paper-card#6]
Sorry to post loads just ideas popping into my head.

If the paper-card has a built in way to change the card color then how feasible would be it to have the card pick a Material color based of the most dominant color of the media image?

This could be pulled together manually with a few separate components though
Polymer/polymer/issues/1185

**Comment by addyosmani** [comment]
We've since migrated this element to

**Comment by AaronLayton** [comment]
Not sure it is needed anymore as we are using css mixins or the styling
