### ISSUE TITLE
Are there any plans on migrating to Polymer 1.0?

### ISSUE THREAD

**Issue by Frikki** [PolymerLabs/paper-card#8]
In the Polymer 1.0 catalog, I am really missing the card elements. I think they are an essential thing of Material Design. Are there any roadmap or plans migrating?

**Comment by zuhairnaqvi** [comment]
?

**Comment by notwaldorf** [comment]
I have the PR ready, just waiting for a final LGTM. Should be released by the end of the week! :tada:

**Comment by Frikki** [comment]
Thanks, Monica. Do you have a link to that PR?

**Comment by notwaldorf** [comment]
Better, I have a link to the updated repo: https://github.com/PolymerElements/paper-card

**Comment by Frikki** [comment]
:dancers:
